---
- name: Add Elasticsearch GPG key
  rpm_key:
    key: "{{ es_gpg_key }}"
    state: present

- name: Add Logstash repository
  template:
    src: {{ logstash_repo_src }}.j2
    dest: /etc/yum.repos.d/{{ logstash_repo }}
    mode: 0644

- name: Install Logstash
  yum:
    pkg: logstash
    state: installed
